// <auto-generated />
namespace KGTMachineLearningWeb.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class configurablecharttyhpe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configurablecharttyhpe));
        
        string IMigrationMetadata.Id
        {
            get { return "201904031829429_configurable chart tyhpe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
